#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DEFAULT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"

ROOT="${WORKSPACE_DEFAULT}"
PROFILE="personal_full"
CLONE_SCHEME="https"
SKIP_CLONE=0

usage() {
  cat <<'EOF'
usage: bootstrap_org_workspace.sh [--root PATH] [--profile personal_full|taylor01_hq_lean] [--clone-scheme https|ssh] [--skip-clone]

Creates or validates a BitPod org workspace root, clones missing repos, writes
minimal root metadata, syncs repo policy packets, and creates the selected
local-workspace profile skeleton.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT="$2"
      shift 2
      ;;
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --clone-scheme)
      CLONE_SCHEME="$2"
      shift 2
      ;;
    --skip-clone)
      SKIP_CLONE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$ROOT"

clone_url() {
  local repo="$1"
  if [[ "$CLONE_SCHEME" == "ssh" ]]; then
    printf 'git@github.com:BitPod-App/%s.git' "$repo"
  else
    printf 'https://github.com/BitPod-App/%s.git' "$repo"
  fi
}

manifest_json() {
  python3 - "$ROOT/bitpod-docs/process/global-agent-policy-distribution-manifest.json" <<'PY'
import json, sys
from pathlib import Path

manifest_path = Path(sys.argv[1])
data = json.loads(manifest_path.read_text())
for repo in data["activeRepos"]:
    print(repo)
PY
}

write_root_metadata() {
  mkdir -p "$ROOT/.codex/environments"
  cat > "$ROOT/.codex/org-workspace.toml" <<EOF
workspace_kind = "github_org_workspace"
workspace_name = "BitPod-App"
github_owner = "BitPod-App"
root_path = "${ROOT}"

[repo_discovery]
mode = "dynamic"

[truth]
root_is_git_repo = false
root_is_org_workspace_container = true
EOF

  cat > "$ROOT/.codex/environments/environment.toml" <<'EOF'
# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
version = 1
name = "BitPod-App"

[setup]
script = ""
EOF

  cat > "$ROOT/.codex/config.toml" <<'EOF'
project_root_markers = []
model_instructions_file = "AGENTS.md"
EOF
}

clone_missing_repos() {
  local repo
  while IFS= read -r repo; do
    [[ -z "$repo" ]] && continue
    if [[ -d "$ROOT/$repo/.git" ]]; then
      echo "ok existing repo: $repo"
      continue
    fi
    echo "cloning repo: $repo"
    git clone "$(clone_url "$repo")" "$ROOT/$repo"
  done < <(manifest_json)
}

create_local_workspace_profile() {
  python3 - "$ROOT/bitpod-docs/process/local-workspace-skeleton-contract.toml" "$PROFILE" "$ROOT/local-workspace" <<'PY'
import sys
from pathlib import Path

contract_path = Path(sys.argv[1])
profile = sys.argv[2]
workspace_root = Path(sys.argv[3])

try:
    import tomllib  # type: ignore[attr-defined]
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]

with contract_path.open("rb") as fh:
    data = tomllib.load(fh)

profiles = data.get("profiles", {})
if profile not in profiles:
    raise SystemExit(f"unknown profile: {profile}")

required = profiles[profile].get("required_paths", [])
workspace_root.mkdir(parents=True, exist_ok=True)
for rel in required:
    (workspace_root / rel).mkdir(parents=True, exist_ok=True)
    print(f"created {workspace_root / rel}")
PY
}

validate_workspace() {
  [[ -f "$ROOT/AGENTS.md" ]] || { echo "missing root AGENTS.md" >&2; exit 1; }
  [[ -f "$ROOT/.codex/org-workspace.toml" ]] || { echo "missing org-workspace.toml" >&2; exit 1; }
  [[ -f "$ROOT/.codex/environments/environment.toml" ]] || { echo "missing environment.toml" >&2; exit 1; }
  [[ -f "$ROOT/bitpod-docs/policies/taylored-policy.md" ]] || { echo "missing taylored-policy.md" >&2; exit 1; }
  [[ -f "$ROOT/bitpod-docs/policies/taylored-policy-rules.md" ]] || { echo "missing taylored-policy-rules.md" >&2; exit 1; }
  [[ -f "$ROOT/bitpod-docs/policies/policy-registry.toml" ]] || { echo "missing policy-registry.toml" >&2; exit 1; }
  python3 "$ROOT/bitpod-docs/scripts/sync_global_agent_policy.py" validate
}

write_root_metadata

if [[ "$SKIP_CLONE" -eq 0 ]]; then
  clone_missing_repos
fi

python3 "$ROOT/bitpod-docs/scripts/sync_global_agent_policy.py" sync
create_local_workspace_profile
validate_workspace

echo "workspace bootstrap complete at $ROOT using profile $PROFILE"
